### ISSUE TITLE
Not compatible with Laravel Mix 6

### ISSUE THREAD

**Issue by desthercz** [GeoffSelby/laravel-mix-artisan-serve#1]
Hi, can you please update the package to support Laravel Mix 6 (which is current Laravel default)? I think the simple edit of package.json would be sufficient.

**Comment by GeoffSelby** [comment]
Absolutely! I’ll add it to the list for tomorrow.

**Comment by GeoffSelby** [comment]
I just published v2 with Laravel Mix 6 compatibility.

**Comment by desthercz** [comment]
Amazing, many thanks.
