### ISSUE TITLE
Choosing Runtime

### ISSUE THREAD

**Issue by ghost** [GeoffSelby/laravel-mix-artisan-serve#3]
This is a feature request.

I need the ability to run some commands to build routes and translations before mix runs.

Would it be possible to add a before or after flag so a user can choose when they should run?

That would be super if it's possible.

Thanks.

**Comment by GeoffSelby** [comment]
I’m sorry but I don’t really understand what you are asking here. This plugin simply spawns a child process running the artisan serve command. 

As far as I know, the artisan serve command only starts a php server and you can’t add a flag to run any special commands.

**Comment by ghost** [comment]
My apologies Geoff, I was looking for the `laravel-mix-serve` project, your name and package was listed in the credits and I mistook your package for the other.

Have a great day.
